name: ps_scratch
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.20=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - audioread==3.0.1
      - certifi==2022.12.7
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fonttools==4.55.0
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.26.2
      - idna==3.4
      - importlib-resources==6.4.5
      - jinja2==3.1.3
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.2
      - pathlib==1.0.1
      - pillow==10.2.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - protobuf==5.28.3
      - psutil==6.1.0
      - pycparser==2.22
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.28.1
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - sentry-sdk==2.18.0
      - setproctitle==1.3.4
      - six==1.16.0
      - smmap==5.0.1
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.2.0+cu121
      - torchaudio==2.2.0+cu121
      - torchvision==0.17.0+cu121
      - tqdm==4.67.0
      - transformers==4.46.2
      - triton==2.2.0
      - typing-extensions==4.9.0
      - urllib3==1.26.13
      - wandb==0.18.7
      - zipp==3.21.0
prefix: /root/miniconda3/envs/ps_scratch
